version: "3.7"

services:
  scout:
    image: sprite75/${SCOUT_ARM_PREFIX}scout_realtime
    restart: unless-stopped
    ports:
      - "${SCOUT_PORT}:5555"
    pid: host

  linespeedtest:
    image: openspeedtest/latest
    restart: unless-stopped
    ports: 
      - "${SPEEDTEST_PORT}:8080"