version: "3.7"

services:
  caddy:
    image: caddy:2.4.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/caddy_config

  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
      # - "8920:8920"
      # - "1900:1900"
      # - "7359:7359"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ${JELLYFIN_MEDIA}:/media
    devices:
      - /dev/vchiq:/dev/vchiq
  
  catcam:
    image: datarhei/restreamer:latest
    restart: unless-stopped
    ports:
      - "${CATCAM_PORT}:8080"
    environment:
      RS_USERNAME: admin
      RS_PASSWORD: ${CATCAM_PASSWORD}
    volumes:
      - ./catcam:/restreamer/db
  
  homeassistant:
    image:  homeassistant/home-assistant:stable
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
