version: "3.7"

services:
  scout:
     extends:
      file: common-services.yml
      service: scout

  linespeedtest:
    extends:
      file: common-services.yml
      service: linespeedtest

  namecheap-ddns:
    image: sprite75/namecheap_ddns
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      DDNS_DOMAIN: ${DDNS_DOMAIN}
      DDNS_SUBDOMAINS: ${DDNS_SUBDOMAINS}
      DDNS_PASSWORD: ${DDNS_PASSWORD}
  
  maxmind-geoip:
    image: maxmindinc/geoipupdate
    restart: unless-stopped
    volumes:
      - ./persistence/maxmind-geoip/GeoIP:/usr/share/GeoIP
    environment:
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}
      GEOIPUPDATE_EDITION_IDS: ${GEOIPUPDATE_EDITION_IDS}
      GEOIPUPDATE_FREQUENCY: ${GEOIPUPDATE_FREQUENCY}
      GEOIPUPDATE_VERBOSE: ${GEOIPUPDATE_VERBOSE}

