version: "3.7"

services:
  scout:
     extends:
      file: common-services.yml
      service: scout

  linespeedtest:
    extends:
      file: common-services.yml
      service: linespeedtest

  namecheap-ddns:
    image: sprite75/namecheap_ddns
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      DDNS_DOMAIN: ${DDNS_DOMAIN}
      DDNS_SUBDOMAINS: ${DDNS_SUBDOMAINS}
      DDNS_PASSWORD: ${DDNS_PASSWORD}
  
  maxmind-geoip:
    image: maxmindinc/geoipupdate
    restart: unless-stopped
    volumes:
      - ./persistence/maxmind-geoip/GeoIP:/usr/share/GeoIP
    environment:
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}
      GEOIPUPDATE_EDITION_IDS: ${GEOIPUPDATE_EDITION_IDS}
      GEOIPUPDATE_FREQUENCY: ${GEOIPUPDATE_FREQUENCY}
      GEOIPUPDATE_VERBOSE: ${GEOIPUPDATE_VERBOSE}

  tandoor_db:
    restart: unless-stopped
    image: postgres:11-alpine
    volumes:
      - ./persistence/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - ./.tandoor.env

  tandoor_web:
    image: vabene1111/recipes
    restart: unless-stopped
    volumes:
      - ./persistence/tandoor/staticfiles:/opt/recipes/staticfiles
      - ./persistence/tandoor/nginx_config:/opt/recipes/nginx/conf.d
      - ./persistence/tandoor/mediafiles:/opt/recipes/mediafiles
    env_file:
      - ./.tandoor.env
    depends_on:
      - tandoor_db

  tandoor_server:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - ${TANDOOR_PORT}:80
    env_file:
      - ./.tandoor.env
    depends_on:
      - tandoor_web
    volumes:
      - ./persistence/tandoor/nginx_config:/etc/nginx/conf.d:ro
      - ./persistence/tandoor/staticfiles:/static
      - ./persistence/tandoor/mediafiles:/media

  bazarr:
    image: lscr.io/linuxserver/bazarr
    restart: unless-stopped
    environment:
      PUID: ${BAZARR_UID}
      PGID: ${BAZARR_GID}
      TZ: ${TZ}
    volumes:
      - ./persistence/bazarr/config:/config
      - ${BAZARR_MOVIES_MOUNT}
      - ${BAZARR_TV_MOUNT}
    ports:
      - ${BAZARR_PORT}:6767

