version: "3.7"

services:
  caddy:
    image: caddy:2.4.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./persistence/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./persistence/caddy/data:/data
      - ./persistence/caddy/config:/caddy_config
  
  duckdns:
    image: linuxserver/duckdns:arm32v7-latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINS}
      TOKEN: ${DUCKDNS_TOKEN}

  namecheap-ddns:
    build:
      context: ./namecheap-ddns
    environment:
      TZ: ${TZ}
      DDNS_DOMAIN: ${DDNS_DOMAIN}
      DDNS_SUBDOMAINS: ${DDNS_SUBDOMAINS}
      DDNS_PASSWORD: ${DDNS_PASSWORD}

  scout:
    image: sprite75/${SCOUT_ARM_PREFIX}scout_realtime
    restart: unless-stopped
    ports:
      - "5555:5555"
    pid: host

  linespeedtest:
    image: openspeedtest/latest
    restart: unless-stopped
    ports: 
      - "6969:8080"

  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
      # - "8920:8920"
      # - "1900:1900"
      # - "7359:7359"
    volumes:
      - ./persistence/jellyfin/config:/config
      - ./persistence/jellyfin/cache:/cache
      - ${JELLYFIN_MEDIA}:/media
    devices:
      - /dev/vchiq:/dev/vchiq
  
  catcam:
    image: datarhei/restreamer${RESTREAMER_ARM_TAG}:latest
    restart: unless-stopped
    ports:
      - "${CATCAM_PORT}:8080"
    environment:
      RS_USERNAME: admin
      RS_PASSWORD: ${CATCAM_PASSWORD}
    volumes:
      - ./persistence/catcam:/restreamer/db
    tmpfs:
      - /tmp/hls
  
  # homeassistant:
  #   image:  homeassistant/home-assistant:stable
  #   restart: unless-stopped
  #   volumes:
  #     - ./persistence/homeassistant/config:/config
  #     - /etc/localtime:/etc/localtime:ro
  #   privileged: true
  #   networks:
  #     - homeassistant_vlan
  #   cap_add: 
  #     - NET_ADMIN

# networks:
#   homeassistant_vlan:
#     driver: macvlan
#     driver_opts:
#       parent: eth0
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.96.0/24
#           ip_range: 192.168.96.4/32
#           gateway: 192.168.96.1