version: "3.7"

services:
  scout:
     extends:
      file: common-services.yml
      service: scout

  linespeedtest:
    extends:
      file: common-services.yml
      service: linespeedtest

  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - "${JELLYFIN_PORT}:8096"
      # - "8920:8920"
      # - "1900:1900"
      # - "7359:7359"
    volumes:
      - ${JELLYFIN_PERSISTENCE_ROOT}/config:/config
      - ${JELLYFIN_PERSISTENCE_ROOT}/transcodes:/transcodes
      - ${JELLYFIN_PERSISTENCE_ROOT}/cache:/cache
      - ${JELLYFIN_MEDIA}:/media
    environment:
        NVIDIA_DRIVER_CAPABILITIES: all
        NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]

  tubearchivist:
    depends_on:
      - tubearchivist-redis
    image: bbilly1/tubearchivist:v0.1.2
    restart: unless-stopped
    ports:
      - ${TUBEARCHIVIST_PORT}:8000
    volumes:
      - ${TUBEARCHIVIST_MEDIA}:/youtube
      - ${TUBEARCHIVIST_PERSISTENCE_ROOT}/cache:/cache
    environment:
      TZ: ${TZ}
      ES_URL: http://tubearchivist-es:9200
      REDIS_HOST: tubearchivist-redis
      HOST_UID: ${TUBEARCHIVIST_UID}
      HOST_GID: ${TUBEARCHIVIST_GID}
      TA_USERNAME: ${TUBEARCHIVIST_USERNAME}
      TA_PASSWORD: ${TUBEARCHIVIST_PASSWORD}
      ELASTIC_PASSWORD: ${TUBEARCHIVIST_ELASTIC_PASSWORD}
  tubearchivist-redis:
    depends_on:
      - tubearchivist-es
    image: redislabs/rejson:latest
    restart: unless-stopped
    volumes:
      - ${TUBEARCHIVIST_PERSISTENCE_ROOT}/redis:/data
    expose:
      - "6379"
  tubearchivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    restart: unless-stopped
    environment:
      "discovery.type": single-node
      "xpack.security.enabled": "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${TUBEARCHIVIST_ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${TUBEARCHIVIST_PERSISTENCE_ROOT}/es:/usr/share/elasticsearch/data
    expose:
      - "9200"
    
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "${NAVIDROME_PORT}:4533"
    restart: unless-stopped
    environment:
      ND_SPOTIFY_ID: ${NAVIDROME_SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${NAVIDROME_SPOTIFY_SECRET}
      ND_LASTFM_APIKEY: ${NAVIDROME_LASTFM_KEY}
      ND_LASTFM_SECRET: ${NAVIDROME_LASTFM_SECRET}
    volumes:
      - "${NAVIDROME_PERSISTENCE_ROOT}/data:/data"
      - "${NAVIDROME_MEDIA}:/music:ro"

  tdarr:
    image: haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # node port
    environment:
      TZ: ${TZ}
      serverIP: 0.0.0.0
      serverPort: ${TDARR_SERVER_PORT}
      webUIPort: ${TDARR_UI_PORT}
      PUID: ${TDARR_UID}
      PGID: ${TDARR_GID}
      UMASK_SET: 002
    volumes:
      - ${TDARR_PERSISTENCE_ROOT}/server:/app/server
      - ${TDARR_PERSISTENCE_ROOT}/configs:/app/configs
      - ${TDARR_PERSISTENCE_ROOT}/logs:/app/logs
      - ${TDARR_PERSISTENCE_ROOT}/cache:/app/cache
      - ${TDARR_MEDIA}:/media
  tdarr-node:
    image: haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      TZ: ${TZ}
      nodeID: MainNode
      nodeIP: 0.0.0.0
      nodePort: ${TDARR_NODE_PORT}
      serverIP: 0.0.0.0
      serverPort: ${TDARR_SERVER_PORT}
      PUID: ${TDARR_UID}
      PGID: ${TDARR_GID}
      UMASK_SET: 002
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    volumes:
      - ${TDARR_PERSISTENCE_ROOT}/configs:/app/configs
      - ${TDARR_PERSISTENCE_ROOT}/logs:/app/logs
      - ${TDARR_PERSISTENCE_ROOT}/cache:/app/cache
      - ${TDARR_MEDIA}:/media
  
  headshotbox:
    image: sprite75/headshotbox
    ports:
      - "${HEADSHOTBOX_PORT}:4000"
    restart: unless-stopped
    environment:
      - HEADSHOTBOX_ADMIN_STEAMID64
      - HEADSHOTBOX_OPENID_REALM
    volumes:
      - ./persistence/headshotbox/config:/config
      - ${HEADSHOTBOX_DEMOS_ROOT}:/demos
