version: "3.7"

services:
  scout:
     extends:
      file: common-services.yml
      service: scout

  linespeedtest:
    extends:
      file: common-services.yml
      service: linespeedtest

  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - "${JELLYFIN_PORT}:8096"
      # - "8920:8920"
      # - "1900:1900"
      # - "7359:7359"
    volumes:
      - ${JELLYFIN_PERSISTENCE_ROOT}/config:/config
      - ${JELLYFIN_PERSISTENCE_ROOT}/cache:/cache
      - ${JELLYFIN_MEDIA}:/media
    environment:
        NVIDIA_DRIVER_CAPABILITIES: all
        NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]

  tubearchivist:
    image: bbilly1/tubearchivist:latest
    restart: unless-stopped
    ports:
      - ${TUBEARCHIVIST_PORT}:8000
    volumes:
      - ${TUBEARCHIVIST_MEDIA}:/youtube
      - ${TUBEARCHIVIST_PERSISTENCE_ROOT}/cache:/cache
    environment:
      ES_URL: http://tubearchivist-es:9200
      REDIS_HOST: tubearchivist-redis
      HOST_UID: ${TUBEARCHIVIST_UID}
      HOST_GID: ${TUBEARCHIVIST_GID}
    depends_on:
      - tubearchivist-redis
  tubearchivist-redis:
    image: redislabs/rejson:latest
    restart: unless-stopped
    volumes:
      - ${TUBEARCHIVIST_PERSISTENCE_ROOT}/redis:/data
    depends_on:
      - tubearchivist-es
  tubearchivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${TUBEARCHIVIST_PERSISTENCE_ROOT}/es:/usr/share/elasticsearch/data
    
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "${NAVIDROME_PORT}:4533"
    restart: unless-stopped
    environment:
      ND_SPOTIFY_ID: ${NAVIDROME_SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${NAVIDROME_SPOTIFY_SECRET}
      ND_LASTFM_APIKEY: ${NAVIDROME_LASTFM_KEY}
      ND_LASTFM_SECRET: ${NAVIDROME_LASTFM_SECRET}
    volumes:
      - "${NAVIDROME_PERSISTENCE_ROOT}/data:/data"
      - "${NAVIDROME_MEDIA}:/music:ro"

  tdarr:
    image: haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # node port
    environment:
      TZ: ${TZ}
      serverIP: 0.0.0.0
      serverPort: ${TDARR_SERVER_PORT}
      webUIPort: ${TDARR_UI_PORT}
      PUID: ${TDARR_UID}
      PGID: ${TDARR_GID}
      UMASK_SET: 002
    volumes:
      - ${TDARR_PERSISTENCE_ROOT}/server:/app/server
      - ${TDARR_PERSISTENCE_ROOT}/configs:/app/configs
      - ${TDARR_PERSISTENCE_ROOT}/logs:/app/logs
      - ${TDARR_PERSISTENCE_ROOT}/cache:/app/cache
      - ${TDARR_MEDIA}:/media
  tdarr-node:
    image: haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      TZ: ${TZ}
      nodeID: MainNode
      nodeIP: 0.0.0.0
      nodePort: ${TDARR_NODE_PORT}
      serverIP: 0.0.0.0
      serverPort: ${TDARR_SERVER_PORT}
      PUID: ${TDARR_UID}
      PGID: ${TDARR_GID}
      UMASK_SET: 002
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    volumes:
      - ${TDARR_PERSISTENCE_ROOT}/configs:/app/configs
      - ${TDARR_PERSISTENCE_ROOT}/logs:/app/logs
      - ${TDARR_PERSISTENCE_ROOT}/cache:/app/cache
      - ${TDARR_MEDIA}:/media
